feat(vod-platform): First commit
BedrockStreaming/tech.bedrockstreaming.com pull request #289
Opened 2021-12-08 16:21 UTC by vgallissot

First commit on this blogpost describing our video delivery platform and
our journey migrating our VOD from on premiseto the cloud

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +* Conclusion
I was thinking if you can make the table of content clickable ?

```suggestion
* [What Streaming is](#whatStreamingIs)
* [Just In Time Packaging](#jit)
* [Version 1: The quest for self](#version1)
    * [Local cache with Nginx](#localCache)
    * [Network Load Balancer: manages TLS and helps with scaling](#nlb)
    * [Content Delivery Network: Keep it Simple and Stupid](#cdn)
    * [A first conclusion: V2 needs Consistent Hashing](#firstConclusion)
* [Version 2: Let the requests flow](#version2)
    * [HAProxy to make Consistent Hashing](#haproxy)
    * [EC2 costs are reduced by using only Spot instances](#spotInstance)
    * [Production launch on this V2](#productionLaunch)
    * [EC2-other: the financial abyss](#ec2Other)
* [Version 3: Cost Explorer Driven Development](#version3)
    * [Be multi-AZ without inter-AZ traffic](#multiAZ)
    * [Mono-AZs AutoScalingGroups](#monoAZ)
* [Optimizations](#optimization)
    * [Adapt HAProxy config for EC2 bandwidth **throttling**](#adaptHAProxy)
    * [Adjust the hash balance factor so that the scaling is triggered correctly](#balanceFactor)
* [Conclusion](#conclusion)
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Just In Time Packaging
```suggestion
## Just In Time Packaging <a name="jit"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Version 1: The quest for self
```suggestion
## Version 1: The quest for self <a name="version1"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Local cache with Nginx
```suggestion
### Local cache with Nginx <a name="localCache"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Network Load Balancer: manages TLS and helps with scaling
```suggestion
### Network Load Balancer: manages TLS and helps with scaling <a name="nlb"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Content Delivery Network: Keep It Simple and Stupid
```suggestion
### Content Delivery Network: Keep It Simple and Stupid <a name="cdn"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### A first conclusion: V2 needs Consistent Hashing
```suggestion
### A first conclusion: V2 needs Consistent Hashing <a name="firstConclusion"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### HAProxy to make Consistent Hashing
```suggestion
### HAProxy to make Consistent Hashing <a name="haproxy"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Version 2: Let the requests flow
```suggestion
## Version 2: Let the requests flow <a name="version2"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### EC2 costs are reduced by using only Spot instances
```suggestion
### EC2 costs are reduced by using only Spot instances <a name="spotInstance"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Production launch on this V2
```suggestion
### Production launch on this V2 <a name="productionLaunch"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### EC2-other: the financial abyss
```suggestion
### EC2-other: the financial abyss <a name="ec2Other"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Version 3: Cost Explorer Driven Development
```suggestion
## Version 3: Cost Explorer Driven Development <a name="version3"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Be multi-AZ without inter-AZ traffic
```suggestion
### Be multi-AZ without inter-AZ traffic <a name="multiAZ"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Mono-AZs AutoScalingGroups
```suggestion
### Mono-AZs AutoScalingGroups <a name="monoAZ"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Optimizations
```suggestion
## Optimizations <a name="optimization"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Adapt HAProxy config for EC2 bandwidth throttling
```suggestion
### Adapt HAProxy config for EC2 bandwidth throttling <a name="adapHAProxy"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Adjust the hash balance factor so that the scaling is triggered correctly
```suggestion
### Adjust the hash balance factor so that the scaling is triggered correctly <a name="balanceFactor"></a>
```

2021-12-09 09:24 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Conclusion
```suggestion
## Conclusion <a name="conclusion"></a>
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Since V3, we have not made any major changes. However, some optimizations were necessary.
```suggestion
Since V3, we have not made any major architectural changes. However, some optimizations were necessary.
```

Pour insister que l'archi est restée la même, malgré les optims ?
(à toi de voir si c'est bien le sens du message que tu veux faire passer en-dessous)

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +I.E: c5.large have a network bandwidth Up to 10Gbps (burst) but 0.75Gbps baseline bandwidth.
```suggestion
For example, `c5.large` instances have a network bandwidth Up to 10Gbps (burst) but only 0.75Gbps baseline bandwidth.  
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The onset of problems occurs when HAProxy sends a little more traffic to one instance than to the others.
"the onset of problems occurs", je comprends ça comme "le début des problèmes arrive", ça me semble un peu lourd.

Reformuler en "Les problèmes commencent" ?
Peut-être "Troubles start when HAP…" ?

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We will observe poor performance or even service interruptions of this server.
Ces trois phrases, un peu plus liées :

> Troubles start when HAProxy sends a little more traffic to one instance than to the others: USP origin's bandwidth may be throttled at some point… And we will observe poor performance or even service interruptions of this server.

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +It allows to remove from load balancing a server that returns an HTTP error code (50x).
Ces deux phrases, un peu reliées :

> We added `observe layer7` to the `default-server` in our HAProxy backends, to remove servers returning HTTP error codes (5xx) from its load-balancing.

?

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We also added the `retry` and `redispatch` options, which allows to retry a request sent to an unhealthy server on a healthy server. It's not optimal for the cache, but the important thing is that a
```suggestion
We also added the `retry` and `redispatch` options, which allow to retry a request sent to an unhealthy server on a healthy server. It's not optimal for the cache, but what matters is that a client's request is successfully answered.
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +From there, if a USP origin throttles on its network bandwidth or if there is a degradation of service, haproxy will immediately redispatch the request to another server.
```suggestion
Now, if a USP origin throttles on its network bandwidth or if there is a degradation of service, haproxy will immediately redispatch the request to another server.
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We have in the works the addition of an `agent-check`, so that the weight of the servers in HAProxy can be directly defined by an USP origin, if it detects that its bandwidth is throttled.
```suggestion
We are working on adding an `agent-check`, so that the weight of the servers in HAProxy can be directly defined by an USP origin, if it detects that its bandwidth is throttled.
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Adjust the hash balance factor so that the scaling is triggered correctly
```suggestion
### Adjust the hash balance factor so scaling is triggered correctly
```

Pas sûr que ça soit valide, mais ça me semble moins lourd.

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +But all content is not equally popular on our platforms. This affects Consistent Hashing which would result in few servers receiving way more traffic than others. Few servers would be overloaded and
```suggestion
But all contents on our platforms are not equally popular. This affects Consistent Hashing which would result in few servers receiving way more traffic than others. Few servers would be overloaded and the majority would not do much.
```

Le sens de cette proposition : On a plusieurs contenus. Et ce sont les "contenus sur notre plateforme" qui ne sont pas tous "également populaires". Et pas les "contenus" qui "ne sont as également populaires sur notre plateforme". Je crois ?

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +This is what the Consistent Hashing with Bounded Loads allows: to benefit from the Consistent Hashing while balancing the load.
```suggestion
This is what Consistent Hashing with Bounded Loads allows: to benefit from Consistent Hashing, while balancing load.
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +For each load test, we looked at the evolution of :
```suggestion
For each load test, we looked at the evolution of:
```

2021-12-09 09:33 UTC, pmartin commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We had the opportunity to review our architecture 3 times, within a few weeks of each other, even though the migration had begun.
```suggestion
We had the opportunity to review our architecture three times, within a few weeks of each other, even though the migration had begun.
```

2021-12-09 09:34 UTC, christian-vdz commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +    * EC2 costs are reduced by using only Spot instances
```suggestion
    * EC2 costs reduced by using only Spot instances
```

2021-12-09 09:34 UTC, christian-vdz commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +    * Adjust the hash balance factor so that the scaling is triggered correctly
```suggestion
    * Adjust the hash balance factor to correctly trigger scaling
```

2021-12-09 09:34 UTC, christian-vdz commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +A client calls a manifest and chunks to play a video.
```suggestion
A client calls for a manifest and chunks to play a video.  
```

2021-12-09 11:11 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We started by adding haproxy servers between the load balancer and the USP servers.
Yep, j'ai cherché/remplacé :+1:

2021-12-09 12:24 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +I.E: c5.large have a network bandwidth Up to 10Gbps (burst) but 0.75Gbps baseline bandwidth.
I added this suggestion

2021-12-09 12:38 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +I.E: a 90mn video, played in Dash, is cut into 900 chunks plus a single Dash manifest. The same video in HLS, it's 900 different chunks and another manifest: 1802 files written on S3. Add the Smooth
Dans les deux cas, Offline ou JIT, c'est le player qui initie tous les téléchargements de fragments et de manifests. Donc pour moi "played" a tout son sens

2021-12-09 12:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We’re using **LUA** in the Nginx vhost, to cache these 65KB and 15B requests made by USP to the S3 bucket.
oui, l'engraissement est confusant, j'ai viré

2021-12-09 12:44 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We’re using **LUA** in the Nginx vhost, to cache these 65KB and 15B requests made by USP to the S3 bucket.
J'ai pensé à mettre un example de code LUA et ça faisait trop avec l'image en plus

2021-12-09 12:57 UTC, Oliboy50 approved these changes
👏

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The [Unified Streaming](https://www.unified-streaming.com/) software handles these calls. Unified Origin (which we call USP) fetches the associated video from the S3 bucket. It relies on a server man
```suggestion
The [Unified Streaming](https://www.unified-streaming.com/) software handles these calls. Unified Origin (which we call USP) fetches the associated video from a AWS S3 bucket. It relies on a server manifest (.Ism file), stored with the video, to respond with the video format the client requested: Dash, HLS, etc.
```

using `the` would work if we already mentioned that we're using a S3 bucket to store our videos beforehand, here we didn't so it feels weird to read `the` as if it was obviously the case

and since this is the first time we're talking of a AWS service, we should specify `AWS S3` instead of just `S3` because again, it is not obvious that we're using AWS at Bedrock (`S3` only may not be obvious for a GCP user that it refers to some cloud service)

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +In this case, once packaging is done, there is no need to do these calculations anymore: it lightens the architecture and avoids the availability challenges of doing real-time calculations.
```suggestion
In this case, once packaging is done, there is no need to do these calculations anymore: it lightens the architecture and avoids the availability challenges of doing real-time computing.
```

WDYT?

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The [Unified Streaming](https://www.unified-streaming.com/) software handles these calls. Unified Origin (which we call USP) fetches the associated video from the S3 bucket. It relies on a server man
```suggestion
The [Unified Streaming](https://www.unified-streaming.com/) software handles these calls. Unified Origin (which we call USP) fetches the associated video from the S3 bucket. It relies on a server manifest (.ism file), stored with the video, to respond with the video format the client requested: Dash, HLS, etc.
```

I think this is `.ism` but if we just put the letter `i` in uppercase, we read `.LSM` instead

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +I.E: a 90mn video, played in Dash, is cut into 900 chunks plus a single Dash manifest. The same video in HLS, it's 900 different chunks and another manifest: 1802 files written on S3. Add the Smooth
d'ailleurs, j'ai l'impression que l'utilisation de `i.e.` n'est pas souhaitée ici, parce qu'i.e. est plutôt utilisé lorsqu'on souhaite reformuler d'une manière plus explicite et obvious du style :

> I would like you to send me this report as soon as you have finished writing it (i.e. ASAP)

alors que dans notre cas, on a plutôt l'air de donner un exemple de ce que peut représenter du stockage chez nous, donc j'aurais plutôt utilisé `e.g.` au lieu de `i.e.`

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +* load the according .Ism file from s3 (the server manifest)
```suggestion
* load the according .ism file from s3 (the server manifest)
```

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +For each video chunk called from a player, the USP module does another call to the S3 bucket, loading the same .Ism manifest and the same metadata (first 65K and latest 15B).
```suggestion
For each video chunk called from a player, the USP module does another call to the S3 bucket, loading the same .ism manifest and the same metadata (first 65K and latest 15B).  
```

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +To avoid these calls and **reduce S3 costs by 60%**, we added Nginx on these EC2s, between HTTPD and s3, to cache the manifest .Ism files and metadatas of .mp4 video files.
```suggestion
To avoid these calls and **reduce S3 costs by 60%**, we added Nginx on these EC2s, between HTTPD and s3, to cache the manifest .ism files and metadatas of .mp4 video files.  
```

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We use Nginx for caching because we have a solid experience with it, under heavy load, on our on-prem edge servers, which each delivers up to 200Gbps of video traffic. We want to capitalize on this e
```suggestion
We use Nginx for caching because we have a solid experience with it, under heavy load, on our on-prem edge servers, which each delivers up to 200Gbps of video traffic. We want to capitalize on this expertise and avoid spreading ourselves on multiple tools (e.g, Apache Cache module).
```

(I'm not a native English guy, donc peut-être que c'est juste moi qui ne comprend pas ce que vient faire `thin` ici, merci de m'expliquer si c'est le cas)

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Note that replacing USP origins with Spot instances has almost no impact on the cache, as we follow the [AWS best practices for Spot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-pra
```suggestion
Note that replacing USP origins with Spot instances has almost no impact on the cache, as we follow the [AWS best practices for Spot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html): use many different instance types, be multi-AZ and use the "Capacity Optimized" strategy. We observe very few reclaims and in any case, they impact just a few servers among the great variety we use.
```

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We migrated our VOD to the cloud, moving from static servers to an end-to-end auto-scaling and multi-AZ infrastructure. We are now able to handle very high loads, which we could not do on-premise.
```suggestion
We migrated our VOD service to the cloud, moving from static servers to an end-to-end auto-scaling and multi-AZ infrastructure. We are now able to handle very high loads, which we could not do on-premise.  
```

2021-12-09 12:57 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We are thinking about V4 and saving 20% of the costs by removing the NLB. We also identified some possible improvements, adding cache on HAProxy for example, or using HAProxy Agent Check so that the
```suggestion
We are thinking about V4 and saving 20% of the costs by removing the NLB. We also identified some possible improvements, adding cache on HAProxy for example, or using HAProxy Agent Check so that the weight of the servers in HAProxy is driven directly by the servers, using the Amazon metrics on network performances. Another promising performance improvement could be to use HAProxy on ARM, it will be worth testing.
```

2021-12-09 12:57 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The major advantage of NLBs is a single entry point (a CNAME domain name), which distributes the load over n EC2 instances. This is essential for auto-scaling: nothing to configure at the CDN level,
J'ai effectivement modifié pour préciser que nous ne souhaitons pas interragir avec la couche HTTP

2021-12-09 13:20 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +To use the cache as much as possible, we need an adapted load balancing method: [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing).
Fixé, j'ai mis des majuscules partout :+1:

2021-12-09 13:22 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +With Consistent Hashing, we can send all requests for the same video to the same cache server. This would optimize the local Nginx cache and reduce S3 costs.
à ce niveau de la V1, il n'y a pas de Consistent Hashing.
Cette première conclusion est hypothétique, la mise en place qui validera se fait en V2.
Donc ça me semble pertinent de garder "would"

2021-12-09 13:27 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Adjust the hash balance factor so that the scaling is triggered correctly
```
### Adjust the hash balance factor to trigger scaling correctly
```

2021-12-09 13:31 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Version 2: Let the requests flow
Même pas non, j'ai voulu que les titres des trois versions refléttent l'état dans lequel on était quand on s'est lancé dedans:
* version 1 = on se cherche
* version 2 = on sait ce qu'on veut: de la requête en masse . Comment? avec du cache local et du Consistent Hashing
* version 3 = oups, dans notre archi on n'a pas pris en compte certains coûts: on repense l'archie en se basant sur Cost Explorer

2021-12-09 13:33 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### HAProxy to make Consistent Hashing
D'après DeepL, `make` ici a bien son sens de `réaliser`
> HAProxy pour réaliser un hachage cohérent

Ce qui a le sens que je souhaite, donc ça me parait pas mal

2021-12-09 13:36 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +When HAProxy servers sent/received traffic from USP servers, the latter may not be in the same Availability Zone and the traffic between both was billed full price.
yep, corrigé may par might

2021-12-09 13:51 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The idea is to do as well for half the price.
J'aime bien le sens: 
"bon, on a un poil chié dans la colle pour la V2, alors l'idée c'est de faire pareil, mais 1/2 prix"

ça montre notre prise de maturité sur les subtilités d'AWS, l'agilité et qu'on avait quand même fait assez bien pour qu'on ait "juste" besoin de baisser les coûts

Pi vu qu'on est encore en V3, garder au présent ne me choque pas

2021-12-09 14:00 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +### Adjust the hash balance factor so that the scaling is triggered correctly
mis à jour en: Adjust the hash balance factor to correctly trigger scaling

2021-12-09 14:11 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We use Nginx for caching because we have a solid experience with it, under heavy load, on our on-prem edge servers, which each delivers up to 200Gbps of video traffic. We want to capitalize on this e
à priori DeepL en fait la distinction entre se disperser et s'éparpiller

Et avec `thin`, ça devient s'éparpiller, ce qui est bien le sens, ça me parait bon

2021-12-09 14:16 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We migrated our VOD to the cloud, moving from static servers to an end-to-end auto-scaling and multi-AZ infrastructure. We are now able to handle very high loads, which we could not do on-premise.
Ce n'est pas tant un service de VOD que vraiment la diffusion des vidéos que nous avons migré, j'ai donc modifié VOD en video delivery qui est plus cohérent avec le titre

2021-12-09 14:26 UTC, coralinepetit commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We use Nginx for caching because we have a solid experience with it, under heavy load, on our on-prem edge servers, which each delivers up to 200Gbps of video traffic. We want to capitalize on this e
`avoid spreading ourselves too thinly ` ?

2021-12-09 15:32 UTC, coralinepetit approved these changes

2021-12-10 10:20 UTC, tanguyfalconnet requested changes

2021-12-10 10:20 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +See the [dedicated blog post](https://tech.bedrockstreaming.com/hsdo/) to know why we preferred to develop a tool dedicated to this task, which we called HAProxy Service Discovery Operator (HSDO).
```suggestion
See the [dedicated blog post](https://tech.bedrockstreaming.com/hsdo/) to know why we preferred to develop a tool dedicated to this task, which we called HAProxy Service Discovery Orchestrator (HSDO).
```

2021-12-10 10:20 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We were still migrating on-prem to the cloud when we put V3 on prod. That’s why you can see all costs have increased from October to December: we’ve doubled the number of viewers during the period.
Tu dis que les coûts ont augmenté parce que le nombre de viewer augmente, mais tu devrais redire que les coûts "EC2 other" en orange ont bien disparus grâce à la V3,

2021-12-10 10:20 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We have also replaced the multi-AZ AutoScalingGroups by several mono-AZ ones. It gives us a finer scaling that corresponds to the real needs in each AZ. The randomness of the round robin and client r
Le fait de passer de multi à mono AZ est surtout une contrainte de la version 3 de HSDO. Sans ça, on est pas capable de réduire les coûts inter-AZ

2021-12-10 10:20 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +It makes us all the more resilient to an AZ failure.
Et en plus, chaque HAProxy est capable de renvoyer du traffic vers une AZ différente si aucun USp n'est healthy dans son AZ (=fallback)

2021-12-10 10:20 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +The goal of the V1 was to quickly provide a platform to our video teams to work on and certify the video players. For ops, it was a first stepping stone building this platform.
Or Infra team, as you said later

2021-12-10 10:21 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +V1 of this platform allowed our video teams to work on new features and new software versions quicker, compared to on-prem. It was also new for infra teams: we wanted to understand how to scale the p
```suggestion
V1 of this platform allowed our video teams to work on new features and new software versions quicker, compared to on-prem. It was also new for Infra teams: we wanted to understand how to scale the platform on AWS to meet our load requirements, making the best use of managed services and auto-scaling, which we did not have on-prem.
```

2021-12-10 10:24 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## How we do streaming <a name="HowWeDoStreaming"></a>
however, this does not seem to be a question here

2021-12-10 10:30 UTC, Oliboy50 commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +V1 of this platform allowed our video teams to work on new features and new software versions quicker, compared to on-prem. It was also new for infra teams: we wanted to understand how to scale the p
aux US ils parlent plutôt de "Infra teams" ou de "Ops teams" ? ou les 2 ?

2021-12-10 10:38 UTC, tanguyfalconnet commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## How we do streaming <a name="HowWeDoStreaming"></a>
Internet says it's good, so I'll close this one :)

2021-12-10 16:31 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +V1 of this platform allowed our video teams to work on new features and new software versions quicker, compared to on-prem. It was also new for infra teams: we wanted to understand how to scale the p
les deux :shrug:

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We are working on adding an `agent-check`, so that the weight of the servers in HAProxy can be directly defined by an USP origin, if it detects that its bandwidth is throttled.
I'd sneek a link to the ENA documentation, it deserves to be known :) https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html#network-performance-metrics

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Our scaling depends on the average server utilization in an AutoScalingGroup. If a few servers are overloaded but the majority is not doing anything, <ins>we don't scale</ins>.
Are you sure this is a correct use of \<ins\>? It's for annotating revisions to a document not formatting.

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +This is what Consistent Hashing with Bounded Loads allows: to benefit from Consistent Hashing, while balancing load.
```suggestion
This is what [Consistent Hashing with Bounded Loads](https://arxiv.org/abs/1608.01350) allows: to benefit from Consistent Hashing, while balancing load.
```

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +[Given to the doc](http://cbonte.github.io/haproxy-dconv/2.3/snapshot/configuration.html#hash-balance-factor):
Given/according ?

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We played the same load test, once using classic Consistent Hashing, a second time using bounded loads:
_same load test_ ? another was not mentionned ?

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +There may be contents much more solicited than others, the load will be balanced and our autoscaling will be activated.
```suggestion
There may be contents that are much more solicited than others, the load will then be balanced and our autoscaling will be activated.
```

2021-12-10 17:13 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We are thinking about V4 and saving 20% of the costs by removing the NLB. We also identified some possible improvements, adding cache on HAProxy for example, or using HAProxy Agent Check so that the
```suggestion
We are thinking about V4 and saving 20% of the costs by removing the NLB. We also identified some possible improvements, adding cache on HAProxy for example, or using HAProxy Agent Check so that the weight of the servers in HAProxy is driven directly by the servers, using the Amazon metrics on network performances. Another promising performance improvement could be to use HAProxy on ARM as Graviton type instances offer significant discounts, it will be worth testing.
```

2021-12-14 12:28 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +To stream video, we cut each video file in 6 seconds chunks. The video player loads the associated manifest, which lists these pieces and in which order it must read them. It then downloads the first
I also like Tanguy's proposal. Keeping it as it's easier to read

2021-12-14 12:28 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Many devices, especially connected TVs or old Android versions, are not compatible with CMAF, which is why the rest of this article will focus on Dash/HLS in JITP.
Indeed, I just added it, thanks

2021-12-14 12:28 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +## Version 1: The quest for self <a name="version1"></a>
Yes it was. We didn't knew what to expect so we tried things :shrug:

2021-12-14 12:28 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +* load the specific chunk in the video, according to the player’s information: bitrate, language, etc. (still on S3)
:100:

2021-12-14 12:49 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +This is what Consistent Hashing with Bounded Loads allows: to benefit from Consistent Hashing, while balancing load.
I already shared Vimeo's rex on this subject earlier in the article: https://www.haproxy.com/user-spotlight-series/haproxy-load-balancing-at-vimeo/https://www.haproxy.com/user-spotlight-series/haproxy-load-balancing-at-vimeo/

I don't think it's necessary to add another link for the same matter ?

2021-12-14 12:49 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +There may be contents much more solicited than others, the load will be balanced and our autoscaling will be activated.
DeepL finds the first one valid and I find it easier to read: I prefer to keep it that way

2021-12-14 13:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +<center><i>v1 of our VOD platform</i></center>
In theory: Yes
In practice: No

It's ugly as fuck with <figcaption> :open_mouth:

2021-12-14 13:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +It makes us all the more resilient to an AZ failure.
oui haproxy full Spot instances aussi, donc oui, ils peuvent se faire reclaim

2021-12-14 13:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +It makes us all the more resilient to an AZ failure.
Je n'ajoute pas les détails que t'évoques @tanguyfalconnet , ça rajoute pas mal d'info et c'est pas forcément indispensable ici. C'est plutôt une bonne feature pour nous ;)

2021-12-14 13:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We have also replaced the multi-AZ AutoScalingGroups by several mono-AZ ones. It gives us a finer scaling that corresponds to the real needs in each AZ. The randomness of the round robin and client r
vu ensemble, c'est good

2021-12-14 13:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +We were still migrating on-prem to the cloud when we put V3 on prod. That’s why you can see all costs have increased from October to December: we’ve doubled the number of viewers during the period.
yep, c'est juste, j'ai rajouté une phrase le précisant ;)

2021-12-14 14:24 UTC, Meroje commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +This is what Consistent Hashing with Bounded Loads allows: to benefit from Consistent Hashing, while balancing load.
yes, missed it

2021-12-14 14:41 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Note that replacing USP origins with Spot instances has almost no impact on the cache, as we follow the [AWS best practices for Spot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-pra
I added this info, thanks

2021-12-14 14:42 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +[Less visible in the EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/compute-optimized-instances.html#compute-network-performance), one can find the **baseline capacity** for e
yep, we would have included throttles at the very beginning

2021-12-14 14:43 UTC, vgallissot commented on _posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
> +Our scaling depends on the average server utilization in an AutoScalingGroup. If a few servers are overloaded but the majority is not doing anything, <ins>we don't scale</ins>.
No it's not, I've changed to the good old `<u>`

2021-12-15 07:34 UTC, merged