feat: add article about cloudfront for web applications
BedrockStreaming/tech.bedrockstreaming.com pull request #292
Opened 2022-01-30 18:11 UTC by Slashgear

Here's an article I've been working on for a while about Cloudfront and how we use it on the web at Bedrock.

I already had @pmartin pre-review the overall draft a while back. Having done a very/too long article he rightly suggested to cut it into two parts.

So here is the first part of this article which deals with the subject of CDN and its usefulness.

In the second part it will be more about good practices and patterns that we have set up on the web side and that we find interesting to share.

2022-01-31 08:10 UTC, kennydee requested changes

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +CDN for Content Delevery Network is a service allowing the delivery of content to users across the internet (here our HTML pages and assets).
```suggestion
CDN for Content Delivery Network is a service allowing the delivery of content to users across the internet (here our HTML pages and assets).
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Being in Lyon, we sometimes get answers from the Pop de Milan.
```suggestion
Being in Lyon (France), we sometimes get answers from the POP (Point Of Presence) of Milan (Italia).
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Note that it is very easy to know which cloudfront pop answered you (default setting).
```suggestion
Note that it is very easy to know which Cloudfront POP answered you (default setting).
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +By making available a large number of Pops around the world, it allows us to provide a response to a user as close as possible to their location.
```suggestion
By making available a large number of POPs around the world, it allows us to provide a response to a user as close as possible to their location.
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Each pop is identified by a three letter code that corresponds to the code of the nearest international airport (here: CDG corresponds to Paris Charles de Gaulle airport).
```suggestion
Each POP is identified by a three letter code that corresponds to the code of the nearest international airport (here: CDG corresponds to Paris Charles de Gaulle airport).
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Caching (telling Cloudfront to cache a web page) takes a lot of the load off our node servers because they are not called.
```suggestion
Caching (telling Cloudfront to cache a web page) takes a lot of the load off our Node servers because they are not called.
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Cloudfront also allows you to do "Edge computing": run code directly in Amazon edges and pops instead of doing it in our applications.
```suggestion
Cloudfront also allows you to do "Edge computing": run code directly in Amazon edges and POPs instead of doing it in our applications.
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Lambda at edge (on regional edges servers), Cloudfront function (function that runs on pop servers)), Web Application Firewall, here are some very cool features that will allow you to do usual manipu
```suggestion
Lambda at edge (on regional edges servers), Cloudfront function (function that runs on POP servers)), Web Application Firewall, here are some very cool features that will allow you to do usual manipulations on your requests/responses.
```

2022-01-31 08:10 UTC, kennydee commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +[![Schema of our cloudfront origin architecture simplified](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-archi.png)](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-a
I've got the impression that we present that far too soon.
Should it be the end of the article to show how we use cloudfront to avoid hitting our node for static asset delivery for exemple ? than in the beggining before having cdn explained ?

2022-01-31 09:13 UTC, Slashgear commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +[![Schema of our cloudfront origin architecture simplified](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-archi.png)](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-a
I have drop the schema which will come back in the next part of the article

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +This means that in production today we have NodeJS Express servers running in production to return pre-rendered HTML pages on the server side.
Maybe the two sentences could become one?
```
The web application works in SSR (Server Side Rendering) mode: we have NodeJS Express servers returning pre-rendered HTML pages.
```

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +[![Schema of our cloudfront origin architecture simplified](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-archi.png)](/images/posts/2022-01-31-cloudfront-web-streaming-platform/web-a
+1

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +**To answer these problems, the use of a CDN seemed necessary to us.**
Are these "problems"? Or, as French would say, "problématiques"?
Not sure what the right English word is… "concerns"?

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +CDN for Content Delivery Network is a service allowing the delivery of content to users across the internet (here our HTML pages and assets).
```suggestion
CDN for Content Delivery Network is a service delivering content to users across the internet (here our HTML pages and assets).
```

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +By making available a large number of POPs around the world, it allows us to provide a response to a user as close as possible to their location.
```suggestion
With a large number of POPs around the world, it helps us provide a response to each user as close as possible to their location.
```

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Different [price classes](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PriceClass.html) allow you to choose the global "zone" in which your application should be available in or
The previous sentence uses "us" while this one uses "you". I kinda see why you did that, but it's a bit surprising when reading…

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Different [price classes](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PriceClass.html) allow you to choose the global "zone" in which your application should be available in or
"zone" -> "area" ?

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +The best solution for load problems is the cache.
I wouldn't say "the" cache. 
Maybe "… is caching" ?

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Cloudfront service makes it easy to cache responses at the server edge.
Does "the server edge" (= "le bord du serveur") mean what you wanted to say?
Maybe "the edge server" (= "le serveur du bord")? Or even "at edge servers" (= "les serveurs des bords") ?

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Finally, by using regional Edge, hundreds of end server edges do not contact your origin (your application) when the cache is invalidated or exceeded.
"end server edges" == POP ?

there are many places you are using "edge", and both REC and POP are edges. But in some cases, using REC or POP instead of "edge" might be more clear. Like here ;-)

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +[![regional edge usage with Cloudfront](/images/posts/2022-01-31-cloudfront-web-streaming-platform/regional.png)](/images/posts/2022-01-31-cloudfront-web-streaming-platform/regional.png)
Font size of the schema is much too small, I think. (same for other schemas, but this one is even smaller)

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Good per-level cache management even allowed us to completely invalidate the cache of a Cloudfront distribution a few minutes before the start of an event without generating huge traffic on our serve
This is scary :-D
Not something I would ever advise ^^

2022-01-31 09:36 UTC, pmartin commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +And that's it for this first article, in the next part (and normally the last one) you will be able to find some patterns and examples of how to use Cloudfront to distribute a high traffic web site.
Instead of speaking of "vous trouverez des exemples de comment utiliser CF sur un site à fort trafic", formulating this around our XP might be more interesting: "vous découvrirez comment nous avons mis certains patterns en application sur nos sites…" ?

2022-01-31 09:45 UTC, Slashgear commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +[![regional edge usage with Cloudfront](/images/posts/2022-01-31-cloudfront-web-streaming-platform/regional.png)](/images/posts/2022-01-31-cloudfront-web-streaming-platform/regional.png)
Yes but user can zoom in or event open it in a dedicate tab,, image is a link

2022-01-31 16:19 UTC, vgallissot reviewed
You added file `web-archi.png` but you don't load it in this article, is it voluntary?
Nice article!
The different sections would gain in readability by being in separate paragraphs IMHO.
IMHO, the notion of cache can be put forward earlier in the article, which would also help to understand why we gain in response-time using a CDN

2022-01-31 16:19 UTC, vgallissot commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Cloudfront service makes it easy to cache responses at the server edge.
this part is not present in the definition of a CDN explained above: the cache, whereas it is however an essential notion of a CDN.
Reading this sentence, I have the impression that Cloudfront has "innovated" by adding caching when it is the main feature expected from a CDN.
Did I misunderstand or is this the meaning you want from your sentence?

2022-01-31 16:19 UTC, vgallissot commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Caching (telling Cloudfront to cache a web page) takes a lot of the load off our Node servers because they are not called.
maybe you can add a Hit/Miss graph here ?

2022-01-31 16:19 UTC, vgallissot commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Caching objects in Cloudfront is also about improving response times.
I'm a bit confused: you already talked about _time to first byte_ earlier.
The two are linked, why did you choose to separate them?

2022-01-31 16:19 UTC, vgallissot commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +Cloudfront also allows you to do "Edge computing": run code directly in Amazon edges and POPs instead of doing it in our applications.
I identify several subsections in this paragraph, which would be relevant to separate into separate paragraphs, WYT?

2022-02-07 09:33 UTC, Oliboy50 approved these changes

2022-03-08 18:13 UTC, Slashgear commented on _posts/2022-01-31-cloudfront-web-streaming-platform-part-1.md
> +title: "How AWS Cloudfront is helping us deliver our Web streaming platform ? - Part 1"
```suggestion
title: "How AWS Cloudfront is helping us deliver our Web streaming platform? - Part 1"
```

2022-03-08 20:39 UTC, vgallissot approved these changes
Nice one, good job on reviews :wink:

2022-03-08 20:39 UTC, vgallissot commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +- [More efficient Load Balancing and Caching at AWS, using Consistent Hashing and HAProxy](https://tech.bedrockstreaming.com/hsdo/)
```suggestion
- [More efficient Load Balancing and Caching at AWS, using Consistent Hashing and HAProxy](https://tech.bedrockstreaming.com/2021/11/18/hsdo.html)
```

2022-03-08 20:39 UTC, vgallissot commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +- [Scaling Bedrock video delivery to 50 million users](https://tech.bedrockstreaming.com/scaling-bedrock-video-delivery-to-50-million-users/)
```suggestion
- [Scaling Bedrock video delivery to 50 million users](https://tech.bedrockstreaming.com/2021/12/15/scaling-bedrock-video-delivery-to-50-million-users.html)
```

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +- [Part 2 - How do we use a CDN to improve our service? Some examples and patterns (in construction 🚧)](/)
This is not formated as a list, in the HTML preview, on the index page of the blog.
=> Maybe use something else as the "short text" for the index page?

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +The web is a major platform for the distribution of our customers' content at Bedrock.
"Bedrock" > add link to corporate site?

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +The web application works in SSR (Server Side Rendering) mode: we have NodeJS Express servers returning pre-rendered HTML pages.
Beginning of this sentence is duplicated?

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +![Worldmap of AWS cloudfront edges](/images/posts/cloudfront-web-streaming-platform/edges.png)
Source for this illustration?

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +Being in Lyon (France), we sometimes get answers from the POP (Point Of Presence) of Milan (Italia).
You explain "POP" here, but it is already used earlier => explain the first time it appears?

2022-03-14 08:13 UTC, pmartin commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +Cloudfront also allows you to do "Edge computing": run code directly in Amazon edges and POPs instead of doing it in our applications.
Most of the article is written with a "us" / "our" form. This sentence and the one after that are written with a "you" / "your" form. Why?

2022-03-14 08:42 UTC, Slashgear commented on _posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md
> +- [Part 2 - How do we use a CDN to improve our service? Some examples and patterns (in construction 🚧)](/)
It is render as a List on te preview, maybe clear your cache :)

2022-03-14 12:55 UTC, merged