feat: add an article about spikes
BedrockStreaming/tech.bedrockstreaming.com pull request #370
Opened 2022-08-23 11:59 UTC by EtienneDOYON

2022-08-23 13:25 UTC, Slashgear commented on _posts/2022-08-23-how-to-spike.md
> +</center> <br/>
Our blog handle nicely code snippet with colors, maybe you could directly add your gherkin as test in the markdown file.
Thus it is better for a11y

2022-08-24 09:59 UTC, Slashgear approved these changes

2022-08-24 09:59 UTC, Slashgear commented on _posts/2022-08-23-how-to-spike.md
> +---
```suggestion
---
layout: post
title: "Les spikes : quand, comment, pour quoi faire ?"
description: "Décomposer une tâche complexe, de A à Z"
author: e_doyon
tags: [spike, methodologie, cytron, tech]
language: fr
color: rgb(255,128,0)
permalink: how-to-spike
---
```

2022-08-24 12:03 UTC, CruuzAzul approved these changes

2022-08-24 13:40 UTC, kennydee approved these changes
👏 Sujet bien sympa ! :)

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +En gros, le but d’un spike, c’est de répondre à la question *“Comment on fait ?”*. Le but d’un spike est de finir avec un prototype de code qui répond à une question, grâce à une série de petites éta
```suggestion
En gros, le but d’un spike, c’est de répondre à la question *“Comment on fait ?”* avec un prototype de code réalisé grâce à une série de petites étapes simples. Un spike n’est pas une formule magique qui va vous permettre de réaliser la tâche impossible que votre client vous a donné. En revanche, le spike va vous permettre de savoir si la tâche impossible ou compliquée à première vue est en fait possible, et si oui, comment.
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +Votre objectif final est de réaliser tout ce que vous avez sur cette liste : strictement rien de moins, mais aussi strictement rien de plus ! Pas de demande implicite de type “Ah mais je voulais auss
```suggestion
Votre objectif final est de réaliser tout ce que vous avez sur cette liste : strictement rien de moins, mais aussi strictement rien de plus ! Pas de demande implicite de type “Ah mais je voulais aussi que l’image soit visible en noir et blanc” : si ce n’est pas sur la liste, ce n’est pas à faire.
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +Cette liste peut être écrite selon votre format favori : un cahier des charges, une série de directives *Gherkin*, l’important c’est qu’elle soit écrite, claire et précise. En d’autres termes, vous é
```suggestion
Cette liste peut être écrite selon votre format favori : un cahier des charges, une série de directives *Gherkin*, l’important c’est qu’elle soit écrite, claire et précise. En d’autres termes, vous définissez ici votre propre cahier des charges.
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +Pour commencer, isolez une partie de votre projet et de vos points objectifs. Il existe plusieurs moyens de s’y prendre : créer un nouveau projet, créer une nouvelle page avec seulement composants, d
```suggestion
Pour commencer, isolez une partie de votre projet et de vos points objectifs. Il existe plusieurs moyens de s’y prendre : créer un nouveau projet, créer une nouvelle page avec seulement quelques composants, décharger votre backend… On veut un environnement le plus clean possible.
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +Beaucoup de projets sont vieux, et si mal conçus qu’il [aurait fallu jeter au bout de deux ans](/2021/09/01/bonnes-pratiques-web). On cherche ici à se détacher au maximum de cette dette technique.
```suggestion
Beaucoup de projets sont vieux, et si mal conçus qu’il [aurait fallu les jeter au bout de deux ans](/2021/09/01/bonnes-pratiques-web). On cherche ici à se détacher au maximum de cette dette technique.
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +Maintenant seulement, vous pouvez prendre votre clavier, et coder. Regardez comment implémenter chacun de ces points dans votre code propre et épuré. Ça fonctionne du premier coup ? Génial, notez com
```suggestion
Maintenant seulement, vous pouvez prendre votre clavier, et coder. Regardez comment implémenter chacun de ces points dans votre code propre de manière épuré. Ça fonctionne du premier coup ? Génial, notez comment vous avez fait ! Ça ne marche pas ? Dommage, mais ce n’est pas une raison pour Ctrl+Z et recommencer. Notez bien ce qui n’a pas marché, avant de retenter ! Si ça ne marche toujours pas au bout de 2/3 essais, pas de soucis, n’hésitez pas à laisser ce point de côté et passer à un autre. Mais notez bien tout, car cela va vous servir très bientôt !
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +# L’instant doc 📝
```suggestion

# L’instant doc 📝 
```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +
```suggestion

```

2022-08-24 13:40 UTC, kennydee commented on _posts/2022-08-23-how-to-spike.md
> +
ou alors un sous titre "conclusion" ?

2022-08-25 13:56 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +C’est une histoire bien connue, dans la vie de n’importe quel développeur : un ticket arrive dans le backlog, décrivant une problématique bien complexe. C’est parfois une question de technologie inco
Répétition de "bien"

2022-08-25 13:56 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Maintenant seulement, vous pouvez prendre votre clavier, et coder. Regardez comment implémenter chacun de ces points dans votre code propre de manière épurée. Ça fonctionne du premier coup ? Génial,
Répétition de "notez bien"

2022-08-25 13:57 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Puis, écrivez ici un compte-rendu de votre aventure. Présentez l’origine de votre spike (Le **Pourquoi**), ce que vous avez tenté (Le **Comment**). Expliquez ce qui a marché et ce qui n’as pas marché
"Puis, écrivez ici". Le ici ne correspond à rien de très précis.

2022-08-25 13:57 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Puis, écrivez ici un compte-rendu de votre aventure. Présentez l’origine de votre spike (Le **Pourquoi**), ce que vous avez tenté (Le **Comment**). Expliquez ce qui a marché et ce qui n’as pas marché
```suggestion
Puis, écrivez ici un compte-rendu de votre aventure. Présentez l’origine de votre spike (Le **Pourquoi**), ce que vous avez tenté (Le **Comment**). Expliquez ce qui a marché et ce qui n’a pas marché : cela vous servira lorsque vous implémenterez vraiment la feature !
```

2022-08-25 13:58 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Enfin, écrivez également les étapes qu’il faudrait suivre pour terminer la feature : ajoutez un maximum de détails techniques ici. Ce sera autant de problématiques en moins pour le pauvre dev qui va
```suggestion
Enfin, écrivez également les étapes qu’il faudrait suivre pour terminer la feature : ajoutez un maximum de détails techniques. Ce sera autant de problématiques en moins pour le pauvre dev qui va récupérer les US après vous.
```

2022-08-25 13:58 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Les mêmes points qu’indiqués ci-dessus continuent de s’appliquer : Notez ce que vous avez tenté et les soucis rencontrés avec chaque implémentation. Puis, continuez le processus détaillé ici : Ce n’e
```suggestion
Les mêmes points qu’indiqués ci-dessus continuent de s’appliquer : notez ce que vous avez tenté et les soucis rencontrés avec chaque implémentation. Puis, continuez le processus détaillé ici : ce n’est pas parce que votre code n’as pas fonctionné qu’il ne doit surtout pas être présenté. Peut-être un de vos collègues trouvera-t-il la ligne qui vous manque, ou le point-virgule que vous avez oublié : Mais peut-être aussi qu’il vous aidera à comprendre ensemble pourquoi la solution ne fonctionne pas dans votre cadre.
```

2022-08-25 14:00 UTC, EtienneDOYON commented on _posts/2022-08-23-how-to-spike.md
> +Pour commencer, isolez une partie de votre projet et de vos points objectifs. Il existe plusieurs moyens de s’y prendre : créer un nouveau projet, créer une nouvelle page avec seulement quelques comp
```suggestion
Pour commencer, isolez une partie de votre projet et de vos points objectifs. Il existe plusieurs moyens de s’y prendre : créer un nouveau projet, créer une nouvelle page avec seulement quelques composants, décharger votre backend… On veut un environnement le plus propre possible.
```

2022-08-26 07:59 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Faire un spike ? Quelle excellente idée ! Encore faudrait-il savoir ce qu’est un spike, comment ça marche, et à quoi ça sert.
```suggestion
Faire un spike ? Quelle excellente idée ! Encore faudrait-il savoir ce qu’est un spike, comment ça marche, et à quoi ça sert.  
```
retour à la ligne

2022-08-26 08:01 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Si ce n’est pas fait, écrivez noir sur blanc les lignes exactes qui vont définir votre tâche comme finie. Que ce soit connecter votre utilisateur de façon sécurisée, afficher une vidéo sans heurt, ou
```suggestion
Si ce n’est pas fait, écrivez noir sur blanc les lignes exactes qui vont définir votre tâche comme finie. Que ce soit connecter votre utilisateur de façon sécurisée, afficher une vidéo sans heurt, ou juste avoir une page qui clignote en blanc et bleu, il faut que vous ayez une liste de *bullet points*, qui définit précisément ce que vous voulez faire.  
```

2022-08-26 08:02 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Votre objectif final est de réaliser tout ce que vous avez sur cette liste : strictement rien de moins, mais aussi strictement rien de plus ! Pas de demande implicite de type “Ah mais je voulais auss
```suggestion
Votre objectif final est de réaliser tout ce que vous avez sur cette liste : strictement rien de moins, mais aussi strictement rien de plus ! Pas de demande implicite de type “Ah mais je voulais aussi que l’image soit visible en noir et blanc” : si ce n’est pas sur la liste, ce n’est pas à faire.  
```

2022-08-26 08:02 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Cette liste peut être écrite selon votre format favori : un cahier des charges, une série de directives *Gherkin*, l’important c’est qu’elle soit écrite, claire et précise. En d’autres termes, vous d
```suggestion
Cette liste peut être écrite selon votre format favori : un cahier des charges, une série de directives *Gherkin*, l’important c’est qu’elle soit écrite, claire et précise. En d’autres termes, vous définissez ici votre propre cahier des charges.  
```

2022-08-26 08:02 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Je vous vois déjà, votre liste de points en main, à tenter de la faire rentrer dans votre gros projet à grands coups de burin, de vous gratter la tête à comprendre pourquoi ça ne rentre pas, et qu’es
```suggestion
Je vous vois déjà, votre liste de points en main, à tenter de la faire rentrer dans votre gros projet à grands coups de burin, de vous gratter la tête à comprendre pourquoi ça ne rentre pas, et qu’est-ce qui a bien pu casser, cette fois.  
```

2022-08-26 08:03 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Maintenant seulement, vous pouvez prendre votre clavier, et coder. Regardez comment implémenter chacun de ces points dans votre code propre de manière épurée. Ça fonctionne du premier coup ? Génial,
```suggestion
Maintenant seulement, vous pouvez prendre votre clavier, et coder. Regardez comment implémenter chacun de ces points dans votre code propre de manière épurée.  
Ça fonctionne du premier coup ? Génial, notez comment vous avez fait ! Ça ne marche pas ? Dommage, mais ce n’est pas une raison pour Ctrl+Z et recommencer. Notez bien ce qui n’a pas marché, avant de retenter ! Si ça ne marche toujours pas au bout de 2/3 essais, pas de soucis, n’hésitez pas à laisser ce point de côté et passer à un autre. Mais écrivez tout, car cela va vous servir très bientôt !
```

2022-08-26 08:05 UTC, christian-vdz commented on _posts/2022-08-23-how-to-spike.md
> +Pour la dernière étape, je vous conseille de réaliser un tableau d’actions *SMART* afin de définir au mieux les tâches à réaliser. Le principe SMART suppose qu’une tâche doit être composées des cinq
```suggestion
Pour la dernière étape, je vous conseille de réaliser un tableau d’actions *SMART* afin de définir au mieux les tâches à réaliser.  
Le principe SMART suppose qu’une tâche doit être composées des cinq caractéristiques suivantes afin d’être pertinente :
```

2022-08-26 08:07 UTC, christian-vdz requested changes
peux-tu ajouter ces quelques retours à la ligne pour faciliter la lecture ?

2022-08-26 10:31 UTC, fdubost approved these changes
👏

2022-08-26 13:24 UTC, vgallissot approved these changes

2022-08-29 13:19 UTC, merged