feat: Bedrock à l'aws summit 2023
BedrockStreaming/tech.bedrockstreaming.com pull request #411
Opened 2023-04-18 15:01 UTC by Eriwyr

2023-04-18 15:14 UTC, pmartin commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +author: p_martin, l_caillet, v_chabrier
```suggestion
author: [p_martin, l_caillet, v_chabrier]
```
Je me demande si il ne faudrait pas un tableau, ici 🤔

2023-04-18 16:36 UTC, Oliboy50 approved these changes

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Des scénarios de tests de performances ont été effectués à l’aide de K6 pour chacun des points. La pre-production a servi d'environnement de tests avant d'effectuer une validation finale sur la vraie
> La pre-production

=> La préproduction

parce que Wikipédia l'a dit: https://fr.wikipedia.org/wiki/Pr%C3%A9production_(produit)

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Au niveau des clusters kubernetes, les applications ont été redimensionnées à la hausse (mémoire, cpu, HPA) pour anticiper les pics de charge et ne pas seulement se reposer sur du scaling réactif.
> les applications ont été redimensionnées à la hausse (mémoire, cpu, HPA) pour anticiper les pics de charge et ne pas seulement se reposer sur du scaling réactif

le `HPA` c'est pas justement ce qui permet le scaling réactif ?

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Amazon annonce une sortie grand public, prochaine, de son assistant de développement par IA CodeWhisperer (update: depuis, [CodeWhisperer est passé GA](https://aws.amazon.com/blogs/aws/amazon-codewhi
IMO la `update` aurait mérité son propre paragraphe (juste après celui-ci par exemple) avec un `UPDATE` en majuscule pour + de visibilité

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +RGPD est un regroupement de règles qui régissent et protègent les droits des résidents d'Union Européenne. Il porte sur le respect de la confidentialité et la protection des données personnelles. Tou
> Dans le cas présent, RGPD couvre

=> Dans le cas présent, la RGPD couvre

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +- Puce de sécurité Nitro (qui empêche le client d'avoir accès aux composants de l'hôte, procède à la mise à jour des firmwares des composants du serveur, gère le sécure boot afin de contrôler l'état
> composants du serveur, gère le sécure boot

=> composants du serveur et gère le sécure boot

parce que l'énumération se termine avec cet item

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Au delà du chiffrement dont il est principalement question ici, Nitro permet aussi de grandement augmenter les performances des EC2 en limitant l'impact de l'hyperviseur sur le CPU utilisé par les cl
> grignotant ainsi une partie de puissance.

=> grignotant ainsi une partie de la puissance.

voire même "de la puissance des machines." ?

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Tout au long de cette conférence, on sentait bien que le but d'AWS, afin de respecter les données de ses usagers, est de faire en sorte de ne pas pouvoir accéder aux données de ses clients.
```suggestion
Tout au long de cette conférence, on a bien senti que le but d'AWS, afin de respecter les données de ses usagers, est de faire en sorte de ne pas pouvoir accéder aux données de ses clients.
```

ou

```suggestion
Tout au long de cette conférence, on sentait bien que le but d'AWS, afin de respecter les données de ses usagers, était de faire en sorte de ne pas pouvoir accéder aux données de ses clients.
```

ou 

```suggestion
Tout au long de cette conférence, on a bien senti que le but d'AWS, afin de respecter les données de ses usagers, était de faire en sorte de ne pas pouvoir accéder aux données de ses clients.
```

2023-04-18 16:36 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Nous avons commencé à [migrer vers Le Cloud](https://leanpub.com/6cloud) en 2018 et notre premier AWS Summit Paris était en 2019 -- nous y avions d’ailleurs déjà parlé de cette migration ([enregistre
```suggestion
Nous avons commencé à [migrer vers Le Cloud](https://leanpub.com/6cloud) en 2018 et notre premier AWS Summit Paris était en 2019 -- nous y avions d’ailleurs [déjà parlé de cette migration au cours d'un autre événement](https://www.youtube.com/watch?v=xLELSIEt2xA&list=PL2ime9SGTcqcJWATAbNDvSVsTQyMridf3&index=11).
```

2023-04-19 07:28 UTC, christian-vdz commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +author: p_martin, l_caillet, v_chabrier
+1

2023-04-19 07:29 UTC, christian-vdz commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Au niveau des clusters kubernetes, les applications ont été redimensionnées à la hausse (mémoire, cpu, HPA) pour anticiper les pics de charge et ne pas seulement se reposer sur du scaling réactif.
```suggestion
Au niveau des clusters Kubernetes, les applications ont été redimensionnées à la hausse (mémoire, cpu, HPA) pour anticiper les pics de charge et ne pas seulement se reposer sur du scaling réactif. 
```

2023-04-19 07:33 UTC, christian-vdz commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +description: Notre retour sur cette édition de l'AWS Summit Paris 2023
```suggestion
description: Notre retour sur cette édition 2023 de l'AWS Summit Paris
```
c'est plus correct non ?

2023-04-19 08:27 UTC, mere-teresa requested changes
Je ne request que les changes d'orthographe, bien sûr !

[suggestion globale]
Ajouter des liens vers les produits AWS cités (ou leur documentation ;-) ) dans un paragraphe "En Savoir plus" à la fin

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +En plus des deux points précédemment cités, nous verrons aussi comment eTF1 s’est préparé pour la coupe du monde de la FIFA 2022, ou de souveraineté et de son application chez AWS.
[suggestion] UCFirst, mettre des majuscules à "Coupe du Monde"

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Conférence présentée par :
[suggestion] mettre un lien vers le blog tech de eTF1 (s'il existe)

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +eTF1 partage son retour d’expérience sur la coupe du monde de foot 2022 et les défis surmontés pour que leur plateforme de replay myTF1 propose une parfaite expérience utilisateur tout au long de l’é
[suggestion][ortho] Coupe du Monde, avec des majuscules

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +- Authent/backend, les millions d’utilisateurs vont s’authentifier dans une fenêtre de 15 minutes.
[ortho] Je crois qu'en FR c'est "s'identifier" et pas s'authentifier, pour un-e utilisateur-ice

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Des scénarios de tests de performances ont été effectués à l’aide de K6 pour chacun des points. La pre-production a servi d'environnement de tests avant d'effectuer une validation finale sur la vraie
[suggestion] remplacer "la vraie production" par "la production" ou "l'environnement de production final" 

Y a-t-il une "fausse production" ?

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Des scénarios de tests de performances ont été effectués à l’aide de K6 pour chacun des points. La pre-production a servi d'environnement de tests avant d'effectuer une validation finale sur la vraie
[suggestion] Rajouter des virgules

Je propose :

Des scénarios de tests de performances ont été effectués, à l’aide de K6, pour chacun des points. La préproduction a servi d'environnement de test, avant d'effectuer une validation finale sur la production. Du travail a été également réalisé sur les services AWS : par exemple, les tables DynamoDB ont été basculées en mode _OnDemand_, afin de profiter de l’élasticité plus rapide du service, malgré les coûts supplémentaires, comparé au mode provisionné.

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Au niveau des clusters kubernetes, les applications ont été redimensionnées à la hausse (mémoire, cpu, HPA) pour anticiper les pics de charge et ne pas seulement se reposer sur du scaling réactif.
[ortho] CPU (acronyme, en majusc)

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Lors de la compétition, une War Room était ouverte suivant l’importance des matchs. Elle était composée d’intervenant AWS grâce au programme IEM, de personnels techniques eTF1 et de membres du servic
[grammaire] "Elle était composée d’intervenant**s** AWS"

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Chez Bedrock Streaming, nous étions curieux de ce retour d’expérience : nous avons préparé ce même type d’événement lors de l'Euro de football 2020. Les défis à surmonter sont les mêmes que ceux que
[grammaire]  Un seul outil, pas de pluriel 
"Nous avions d’ailleurs développé un outil"

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Chez Bedrock Streaming, nous étions curieux de ce retour d’expérience : nous avons préparé ce même type d’événement lors de l'Euro de football 2020. Les défis à surmonter sont les mêmes que ceux que
[cohérence]
Euro 2020 => majuscule à Euro, partout (ou nulle part...choisissez)
[ortho]
Kubernetes -> majuscule car nom propre

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Cette année encore, nous avons eu la chance de pouvoir partager notre expérience, lors d’une conférence donnée par [Pascal](https://twitter.com/pascal_martin), Principal Engineer et [AWS Hero](https:
[suggestion] ajouter un lien vers la description dans le programme de la conférence (avec le résumé du sujet)

2023-04-19 08:27 UTC, mere-teresa commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +Depuis, que de chemin parcouru ! Cette année, nous pensions moins à Kubernetes, à DynamoDB ou aux optimisations de coûts, sur lesquels nous avons bien bossé depuis 2019. Notre attention était plus at
[suggestion]
Ajouter des liens vers les produits AWS cités (ou leur documentation ;-) ) dans un paragraphe "En Savoir plus" à la fin

2023-04-19 12:45 UTC, Oliboy50 commented on _posts/2023-04-20-aws-summit-paris-2023.md
> +author: p_martin, l_caillet, v_chabrier
il faut bien un tableau d'après @TimotheCrespy 
=> https://github.com/BedrockStreaming/tech.bedrockstreaming.com/pull/412#discussion_r1171266643

2023-04-20 09:16 UTC, christian-vdz commented
Une petite compression des images ajoutés/modifiés pourraient faire du bien. (surtout vu la taille d'affichage)

Un petit coup de https://tinypng.com/ à minima ou https://squoosh.app/
(copyright à Antoine sur ce message comme j'ai cop/col :p)

2023-04-20 15:01 UTC, GeGeGM approved these changes

2023-04-20 15:05 UTC, merged