feat: rex mixit 2023
BedrockStreaming/tech.bedrockstreaming.com pull request #420
Opened 2023-04-25 08:17 UTC by al2b

Retour sur MiXiT 2023

2023-05-16 14:21 UTC, AFerez commented on _posts/2023-04-25-mixit-lyon-2023.md
> +L'objectif était de construire le plus de modèles d'un calendrier de l'avent Lego, donc des modèles petits et (en général) assez simples, nous avions 6 minutes par type d'organisation.Les rôles sont
[espace] Les rôles étaient

2023-05-16 14:21 UTC, AFerez commented on _posts/2023-04-25-mixit-lyon-2023.md
> + - Pilote : Remplie un tableau de suivi des différents postes
Remplit

2023-05-16 14:22 UTC, AFerez commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Première étape, le du Waterfall : chaque rôle devait finir son travail pour 5 cartes avant de passer au suivant.
Supprimer le "du" ;-)

2023-05-16 14:22 UTC, AFerez commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Deuxième étape, le Scrum : chaque rôle peut faire passer une carte au prochain dès que son travaille sur celle-ci est fini.
travail

2023-05-16 14:23 UTC, AFerez commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Au final, nous avons pu terminer 6 cartes (un bug est survenue en cours de route).Le Kanban a permis une avancée plus importante, mais le suivi par le pilote était plus compliqué, car les cartes boug
survenu

2023-05-16 14:52 UTC, mere-teresa requested changes
Je ne demande que les changements relatifs à l'ortho/grammaire.

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Les débats étaient constructifs et les faits effrayants.
[suggestion] expliquer pourquoi les faits étaient effrayants : par exemple, "les faits, issus d'événements vraiment arrivés dans le domaine de l'IT" ou encore "les faits, appuyés par les statistiques de l'INSEE"

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +il y a encore beaucoup à faire aussi bien dans le milieu professionnel que privé.
[suggestion] Ajouter des précisions dans la phrase, je suggère : "il y a encore beaucoup à faire **pour diminuer le sexisme** aussi bien..."

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Tout ça par équipe de 5 personnes et avec des Lego :heart_eyes:.
[grammaire][niveau de langage] Il n'y a pas de verbe dans cette phrase 😄 
Cela peut tout à fait être un parti pris, mais je suis gênée par cette tournure familière

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Chaque personne avait un rôle particulier qui représente les différents rôles d'une équipe de développement standard.
[contenu] Pour être + clair, je suggère "Chaque personne **jouait** un rôle particulier qui représentait les différents rôles"

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Deuxième étape, le Scrum : chaque rôle peut faire passer une carte au prochain dès que son travaille sur celle-ci est fini.
[grammaire] "celle-ci est fini**e**" (il manque le -e final)

2023-05-16 14:52 UTC, mere-teresa commented on _posts/2023-04-25-mixit-lyon-2023.md
> +Dernière étape, le Kanban : comme pour le scrum, une carte peut passer à l'étape d'après, dès qu'elle est terminée.
[ortho] Majuscule au mot "Scrum" pour la cohérence avec le reste de l'article (ou alors on met des minuscules partout)

2023-05-17 05:51 UTC, Slashgear approved these changes

2023-05-17 05:51 UTC, Slashgear commented on _posts/2023-04-25-mixit-lyon-2023.md
> +En guise d'illustration, Marie-Alice a demandé à ChatGPT de se rendre sur son terminal linux, et
```suggestion
En guise d'illustration, Marie-Alice a demandé à ChatGPT de se rendre sur son terminal Linux, et 
```

2023-05-25 12:54 UTC, merged