Euro 2024: Using Fastly Compute
BedrockStreaming/tech.bedrockstreaming.com pull request #453
Opened 2024-11-04 10:57 UTC by pmartin

How we used Fastly Compute for Euro 2024 ;-)

2024-11-05 09:58 UTC, shavounet approved these changes
:ok_hand:

2024-11-05 10:00 UTC, shavounet requested changes

2024-11-05 10:00 UTC, shavounet commented on _posts/2024-11-07-compute-at-edge-personalize-static-pages.md
> +![](/images/posts/2024-11-compute-at-edge/compute-at-edge-monitoring-fastly-censored.png)
Not fully censored !

2024-11-05 16:44 UTC, fragab commented on _posts/2024-11-07-compute-at-edge-personalize-static-pages.md
> +This personalization layer would read some basic data *(does the current user have a subscription? Did they consent to tracking and analytics?)* from a datastore-at-edge and use them to inject identi
It mixes singular and plural, what about `Did he consent to tracking and analytics?`

2024-11-05 17:02 UTC, fragab approved these changes
Great article 👏

2024-11-08 15:34 UTC, fdubost approved these changes
Very clear 👏 
(said by a frontend dev 😄)

2024-11-08 15:34 UTC, fdubost commented on _posts/2024-11-07-compute-at-edge-personalize-static-pages.md
> +As most of our APIs are running in a Kubernetes cluster, you might say *“use auto-scaling!”*, and you’d be kind of right. We are using auto-scaling. But reactive auto-scaling, based on traffic or loa
The open source lin seems not good

2024-11-08 15:34 UTC, fdubost commented on _posts/2024-11-07-compute-at-edge-personalize-static-pages.md
> +<center><ins><strong>Schema 1: one BFF between frontend apps and backend APIs.</strong></ins></center>
Don't know why, but on the preview the legend is stuck to the following paragraph 🤷

2024-11-08 15:46 UTC, pmartin commented on _posts/2024-11-07-compute-at-edge-personalize-static-pages.md
> +<center><ins><strong>Schema 1: one BFF between frontend apps and backend APIs.</strong></ins></center>
😭 I tried a few things and ended-up adding a `<br>` after each legend. Yeah, ugly… But works 🤷‍♂️ (and I don't dare touching CSS)

2024-11-08 17:00 UTC, shavounet approved these changes

2024-11-12 06:54 UTC, merged